<?php
define('FILER_CRON', 'filer:cron');

/**
 * Implements hook_cron_queue_info().
 */
function filer_cron_queue_info() {
  $queues[FILER_CRON] = array(
    'worker callback' => 'filer_cron_callback',
    'time' => 30,
  );

  return $queues;
}

/**
 * Main cron callback.
 * This function will open the file and write the return value of the given callback function, if the return value is a string.
 * Passes the provided data, file contents, the filehandle and a status indicator to the callback.
 * Status indicator will be 'first', empty or 'last'.
 */
function filer_cron_callback($data) {
  $filer = new Filer($data['id']);
  $filer_row = $filer->getFiles($data['frid']);
  if (!isset($filer_row['callback'])) {
    $filer->deleteRow($data['frid']);
    watchdog('filer', 'Invalid data in filer table', $filer_row);
    return;

  }
  $callback = $filer_row['callback'];
  $fn = $data['filepath'];
  $tmp_fn = $data['filepath'] . '.tmp';
  if (!function_exists($callback)) {
    watchdog('filer', 'callback function %func was not found', array('%func' => $callback));
    return;
  }
  if (!$fh = fopen($tmp_fn, $data['fmode'])) {
    watchdog('filer', 'could not open file: %file', array('%file' => $tmp_fn));
    return;
  }
  $content = '';
  if (!empty($data['read'])) {
    clearstatcache(TRUE);
    $content = fread($fh, filesize($tmp_fn));
  }
  $return = call_user_func($callback, $data['data'], $content, $fh, $data['status']);
  if (is_string($return) && fwrite($fh, $return) === FALSE) {
    watchdog('filer', 'could not write to %file', array('%file' => $tmp_fn));
  }
  fclose($fh);
  if ($data['status'] === 'last') {
    if (!rename($tmp_fn, $fn)) {
      watchdog('filer', 'could not rename %file to %nfile', array('%file' => $tmp_fn, '%nfile' => $fn));
    }
    $filer->finish($data['frid']);
  }
}

class Filer {

  private $id;

  /**
   * @param $id String  Arbitrary string used to differentiate between Filer data.
   * @throws ErrorException when $id is not a non-empty string
   */
  public function __construct($id) {
    if (!is_string($id) || empty($id)) {
      throw new ErrorException('Filer::__construct($id) requires a non-empty string as first param.');
    }
    $this->id = $id;
  }

  /**
   * Add new filer task.
   *
   * @param   $filepath   String    Absolute filepath.
   * @param   $items      Array     Array of items, each item is passed to the given callback function.
   * @param   $callback   String    Reference to a function, called for each item in $items.
   * @param   $filemode   String    @see http://php.net/manual/en/function.fopen.php: mode.
   * @param   $read       bool      Whether to read the file and pass the contents to $callback.
   * @return              bool      FALSE on failure
   */
  public function add($filepath, $items, $callback, $filemode = 'a', $read = FALSE) {
    $fmstrlen = strlen($filemode);
    if (!in_array(substr($filemode, 0, 1), array('r', 'w', 'a', 'x', 'c')) || !in_array(substr($filemode, 1, 1), array('+', '')) || $fmstrlen > 2 || $fmstrlen == 0) {
      watchdog('filer', 'Invalid filemode given');
      return FALSE;
    }
    if ($read && $fmstrlen == 1 && in_array($filemode, array('a', 'w', 'x', 'c'))) {
      $filemode .= '+';
    }
    $insert = array('id' => $this->id, 'callback' => $callback, 'file' => $filepath);
    watchdog('', '', $this->id);
    $frid = db_insert('filer')->fields($insert)->execute();
    if (is_null($frid)) {
      watchdog('filer', 'Could not insert row into filer table');
      return FALSE;
    }
    $q = DrupalQueue::get(FILER_CRON);
    $item_count = count($items);
    $i = 0;
    foreach ($items as $item) {
      $i++;
      $status = '';
      if ($i == $item_count) {
        $status = 'last';
      }
      elseif ($i == 1) {
        $status = 'first';
      }
      $q->createItem(array(
        'frid' => $frid,
        'id' => $this->id,
        'status' => $status,
        'read' => $read,
        'fmode' => $filemode,
        'filepath' => $filepath,
        'data' => $item
      ));
    }
    return TRUE;
  }

  /**
   * Unlink file from filesystem and delete from db if successful.
   *
   * @param   $frid   Int   FilerFileId.
   * @return          bool  FALSE on failure.
   */
  public function deleteFile($frid) {
    $row = $this->getFiles($frid);
    if (isset($row['file']) && unlink($row['file'])) {
      $this->deleteRow($frid);
      return TRUE;
    }
    return FALSE;
  }

  /**
   * Get all FilerFile rows. Filtering out those not matching given $frid or/and $path.
   *
   * @param   $frid   Int     FilerFileId.
   * @param   $path   String  Absolute path to the file.
   * @return          mixed
   */
  public function getFiles($frid = NULL, $path = NULL) {
    $qry = db_select('filer', 'f');
    $qry->fields('f', array('frid', 'id', 'callback', 'file', 'finished'));
    $qry->condition('f.id', $this->id);
    if (is_numeric($frid)) {
      $qry->condition('f.frid', $frid);
    }
    if (is_string($path)) {
      $qry->condition('f.file', $path);
    }
    $result = $qry->execute();
    if (!is_null($frid)) {
      return $result->fetchAssoc();
    }
    else {
      return $result->fetchAllAssoc('frid');
    }
  }

  /**
   * Internal filer function!
   * Sets filetask to finished.
   *
   * @param   $frid   Int   FilerFileId.
   * @private
   */
  public function finish($frid) {
    $row = $this->getFiles($frid);
    if (!empty($row)) {
      db_delete('filer')->isNotNull('finished')->condition('file', $row['file'])->execute();
    }
    db_update('filer')->fields(array('finished' => time()))->condition('frid', $frid)->condition('id', $this->id)->execute();
  }

  /**
   * Internal filer function!
   * Deletes one or more rows from the filer table.
   *
   * @param   $frid   Int   FilerFileId.
   * @private
   */
  public function deleteRow($frid) {
    db_delete('filer')->condition('frid', $frid)->condition('id', $this->id)->execute();
  }

}
